version: '3.9'

services:
  backend:
    build:
      context: ./portuense-backend
    volumes:
      - ./portuense-backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=dev-secret
      - DJANGO_ALLOWED_HOSTS=*
      - POSTGRES_DB=portuense_db
      - POSTGRES_USER=portuense_user
      - POSTGRES_PASSWORD=portuense_pass
    depends_on:
      - db
    entrypoint: sh /app/entry.sh

  frontend:
    build:
      context: ./portuense-react
    volumes:
      - ./portuense-react:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=portuense_db
      - POSTGRES_USER=portuense_user
      - POSTGRES_PASSWORD=portuense_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
