version: '3.9'

services:
  backend:
    build:
      context: ./portuense-backend
    volumes:
      - ./portuense-backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=dev-secret
      - DJANGO_ALLOWED_HOSTS=*
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - frontend  # Opcional, útil si el backend espera assets o API del frontend

  frontend:
    build:
      context: ./portuense-react
    volumes:
      - ./portuense-react:/app
      - /app/node_modules  # Previene conflictos con host
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    stdin_open: true
    tty: true
