# Generated by Django 5.1.6 on 2025-05-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('categoria', models.CharField(choices=[('Partido', 'Partido'), ('Entrenamiento', 'Entrenamiento')], default='Partido', max_length=20)),
                ('equipo1', models.CharField(default='Racing Club Portuense', max_length=45)),
                ('equipo2', models.CharField(blank=True, max_length=45, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FolderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('p_apellido', models.CharField(max_length=100, null=True)),
                ('s_apellido', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], default='CAD', max_length=20)),
                ('subcategoria', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=6)),
                ('equipo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10)),
                ('posicion', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ha_pagado_cuota', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('query', models.JSONField()),
                ('visible_to', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excels/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excels', to='jugadores.foldergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contrato_por_gol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fijo_ganado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='jugadores.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('carpeta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='jugadores.carpeta')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='jugadores.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='pdfs')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='jugadores.carpeta')),
            ],
        ),
    ]
