# Generated by Django 5.1.6 on 2025-07-13 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariojugador',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentariojugador',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
