# Generated by Django 5.1.6 on 2025-07-30 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_alter_jugador_p_apellido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioDireccionDeportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], help_text='Categoría del equipo (e.g., Infantil)', max_length=20)),
                ('subcategoria', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', help_text='Subcategoría del equipo (e.g., A, B)', max_length=6)),
                ('equipo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Masculino o Femenino', max_length=1)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_modificacion'],
                'unique_together': {('categoria', 'subcategoria', 'equipo')},
            },
        ),
    ]
