# Generated by Django 5.1.6 on 2025-06-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0004_comentariojugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Partido', 'Partido'), ('Entrenamiento', 'Entrenamiento'), ('Reunion', 'Reunión')], default='Partido', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='CeldaExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], max_length=20)),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.CharField(max_length=5)),
                ('valor', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('categoria', 'fila', 'columna')},
            },
        ),
    ]
