# Generated by Django 5.1.6 on 2025-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_alter_evento_categoria_alter_evento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celdaexcel',
            name='equipo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
