# Generated by Django 5.1.6 on 2025-08-08 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_informejugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], help_text='Categoría a la que pertenece esta subcategoría', max_length=20)),
                ('equipo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Equipo (Masculino/Femenino) al que pertenece esta subcategoría', max_length=1)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['categoria', 'equipo', 'codigo'],
                'unique_together': {('codigo', 'categoria', 'equipo')},
            },
        ),
    ]
