# Generated by Django 5.1.6 on 2025-06-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0006_celdaexcel_equipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='celdaexcel',
            unique_together={('categoria', 'fila', 'columna', 'equipo')},
        ),
    ]
