# Generated by Django 5.1.6 on 2025-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0007_tipoentrenamiento_entrenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='tipo',
            field=models.CharField(help_text='Tipo de entrenamiento (ej: Balón parado, Recuperación, Físico, Táctico)', max_length=100),
        ),
    ]
