# Generated by Django 5.1.6 on 2025-06-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0007_alter_celdaexcel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], max_length=20, null=True)),
                ('equipo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='clubes/')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorRival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dorsal', models.PositiveIntegerField(blank=True, null=True)),
                ('posicion', models.CharField(blank=True, max_length=50)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rivales/')),
                ('observaciones', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='jugadores.clubrival')),
            ],
        ),
    ]
