# Generated by Django 5.1.6 on 2025-08-12 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0008_alter_entrenamiento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='name',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], help_text='Categoría del equipo', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='equipo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Equipo (Masculino/Femenino)', max_length=1),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoentrenamiento',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'equipo', 'codigo')},
        ),
        migrations.CreateModel(
            name='InformeJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], help_text='Categoría del equipo', max_length=20)),
                ('subcategoria', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='Subcategoría del equipo', max_length=6)),
                ('equipo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Equipo (Masculino/Femenino)', max_length=1)),
                ('jornada', models.IntegerField(help_text='Número de jornada')),
                ('equipo_rival', models.CharField(help_text='Nombre del equipo rival', max_length=100)),
                ('contenido', models.TextField(help_text='Contenido del informe de la jornada')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_jornada_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-jornada', 'categoria', 'subcategoria', 'equipo'],
                'unique_together': {('categoria', 'subcategoria', 'equipo', 'jornada')},
            },
        ),
        migrations.DeleteModel(
            name='InformeJugador',
        ),
    ]
