# Generated by Django 5.1.6 on 2025-06-09 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0008_clubrival_jugadorrival'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariojugador',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comentariojugador',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='ComentarioRival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_emision', models.DateField(null=True)),
                ('fecha_creacion', models.DateField(null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='jugadores.jugadorrival')),
            ],
        ),
    ]
