# Generated by Django 5.1.6 on 2025-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0010_add_fecha_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informejornada',
            name='fecha_partido',
            field=models.DateField(help_text='Fecha del partido'),
        ),
    ]
