# Generated by Django 5.1.6 on 2025-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0010_comentarioclubrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelPorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], max_length=20)),
                ('equipo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('archivo', models.FileField(upload_to='excels/')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('categoria', 'equipo')},
            },
        ),
        migrations.DeleteModel(
            name='CeldaExcel',
        ),
        migrations.AddField(
            model_name='permisopersonalizado',
            name='vista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
