# Generated by Django 5.1.6 on 2025-06-17 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0011_excelporcategoria_delete_celdaexcel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisopersonalizado',
            name='vista',
        ),
        migrations.CreateModel(
            name='PermisoVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'vista')},
            },
        ),
    ]
