# Generated by Django 5.1.6 on 2025-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0012_remove_permisopersonalizado_vista_permisovista'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria_equipo',
            field=models.CharField(blank=True, choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior')], help_text='Categoría del equipo para partidos (e.g., Infantil)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='equipo_genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Masculino o Femenino', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jugadorrival',
            name='equipo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
