# Generated by Django 5.1.6 on 2025-06-25 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0013_evento_categoria_equipo_evento_equipo_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioclubrival',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentariojugador',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentariojugador',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentariorival',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentariorival',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
