# Generated by Django 5.1.6 on 2025-06-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0014_alter_comentarioclubrival_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadorrival',
            name='equipo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorrival',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
