# Generated by Django 5.1.6 on 2025-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0015_alter_jugadorrival_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisopersonalizado',
            name='categoria',
            field=models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil'), ('SEN', 'Sénior'), ('RIV', 'Rivales')], max_length=10),
        ),
    ]
