# Generated by Django 5.1.6 on 2025-06-30 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0016_alter_permisopersonalizado_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permisopersonalizado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='permisopersonalizado',
            name='subcategoria',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='permisopersonalizado',
            unique_together={('user', 'categoria', 'equipo', 'subcategoria')},
        ),
    ]
