# Generated by Django 5.1.6 on 2025-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0017_alter_permisopersonalizado_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='subcategoria_equipo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='Subcategoría del equipo (e.g., A, B)', max_length=30, null=True),
        ),
    ]
